use crate::registry::metadata::{ModelMetadata, ModelProtocol, ReasoningType};
use std::collections::HashMap;

/// Returns the embedded offline fallback catalog of the 12 verified OpenCode Zen free models.
pub fn get_baseline_models() -> HashMap<String, ModelMetadata> {
    let mut map = HashMap::new();

    let models = vec![
        ModelMetadata {
            id: "muse-spark-1.3-contributor-free".to_string(),
            name: "Muse Spark 1.3 Free".to_string(),
            description: "Multimodal reasoning model from Meta for coding and agentic workflows"
                .to_string(),
            family: "muse".to_string(),
            protocol: ModelProtocol::Responses,
            reasoning: ReasoningType::Effort {
                values: vec![
                    "minimal".to_string(),
                    "low".to_string(),
                    "medium".to_string(),
                    "high".to_string(),
                    "xhigh".to_string(),
                ],
            },
            context_limit: 1048576,
            output_limit: 131072,
            is_free: true,
            created: 1728424000,
            owned_by: "opencode".to_string(),
        },
        ModelMetadata {
            id: "muse-spark-1.2-contributor-free".to_string(),
            name: "Muse Spark 1.2 Free".to_string(),
            description: "Multimodal reasoning model from Meta for coding".to_string(),
            family: "muse".to_string(),
            protocol: ModelProtocol::Responses,
            reasoning: ReasoningType::Effort {
                values: vec![
                    "minimal".to_string(),
                    "low".to_string(),
                    "medium".to_string(),
                    "high".to_string(),
                    "xhigh".to_string(),
                ],
            },
            context_limit: 1048576,
            output_limit: 131072,
            is_free: true,
            created: 1728424000,
            owned_by: "opencode".to_string(),
        },
        ModelMetadata {
            id: "mimo-v2.6-flash-free".to_string(),
            name: "Mimo v2.6 Flash Free".to_string(),
            description: "Ultra-fast multimodal reasoning model with interleaved thinking"
                .to_string(),
            family: "mimo".to_string(),
            protocol: ModelProtocol::ChatCompletions,
            reasoning: ReasoningType::Interleaved,
            context_limit: 262144,
            output_limit: 16384,
            is_free: true,
            created: 1728424000,
            owned_by: "opencode".to_string(),
        },
        ModelMetadata {
            id: "nemotron-3-ultra-free".to_string(),
            name: "Nemotron 3 Ultra Free".to_string(),
            description: "NVIDIA high-performance reasoning model".to_string(),
            family: "nemotron".to_string(),
            protocol: ModelProtocol::ChatCompletions,
            reasoning: ReasoningType::Interleaved,
            context_limit: 131072,
            output_limit: 16384,
            is_free: true,
            created: 1728424000,
            owned_by: "opencode".to_string(),
        },
        ModelMetadata {
            id: "nemotron-3.5-lightning-free".to_string(),
            name: "Nemotron 3.5 Lightning Free".to_string(),
            description: "NVIDIA fast reasoning model".to_string(),
            family: "nemotron".to_string(),
            protocol: ModelProtocol::ChatCompletions,
            reasoning: ReasoningType::Interleaved,
            context_limit: 131072,
            output_limit: 16384,
            is_free: true,
            created: 1728424000,
            owned_by: "opencode".to_string(),
        },
        ModelMetadata {
            id: "space-bunny-free".to_string(),
            name: "Space Bunny Free".to_string(),
            description: "Deep thinking model with multi-tier reasoning effort".to_string(),
            family: "space-bunny".to_string(),
            protocol: ModelProtocol::ChatCompletions,
            reasoning: ReasoningType::Effort {
                values: vec![
                    "low".to_string(),
                    "medium".to_string(),
                    "high".to_string(),
                    "xhigh".to_string(),
                    "max".to_string(),
                ],
            },
            context_limit: 131072,
            output_limit: 16384,
            is_free: true,
            created: 1728424000,
            owned_by: "opencode".to_string(),
        },
        ModelMetadata {
            id: "longcat-2.5-preview-free".to_string(),
            name: "Longcat 2.5 Preview Free".to_string(),
            description: "Extended context model with toggleable reasoning".to_string(),
            family: "longcat".to_string(),
            protocol: ModelProtocol::ChatCompletions,
            reasoning: ReasoningType::Toggle,
            context_limit: 262144,
            output_limit: 16384,
            is_free: true,
            created: 1728424000,
            owned_by: "opencode".to_string(),
        },
        ModelMetadata {
            id: "step-5-preview-free".to_string(),
            name: "Step 5 Preview Free".to_string(),
            description: "Stepfun reasoning model".to_string(),
            family: "step".to_string(),
            protocol: ModelProtocol::ChatCompletions,
            reasoning: ReasoningType::Effort {
                values: vec!["low".to_string(), "medium".to_string(), "high".to_string()],
            },
            context_limit: 131072,
            output_limit: 16384,
            is_free: true,
            created: 1728424000,
            owned_by: "opencode".to_string(),
        },
        ModelMetadata {
            id: "ling-3.1-flash-free".to_string(),
            name: "Ling 3.1 Flash Free".to_string(),
            description: "High speed language model".to_string(),
            family: "ling".to_string(),
            protocol: ModelProtocol::ChatCompletions,
            reasoning: ReasoningType::Toggle,
            context_limit: 131072,
            output_limit: 16384,
            is_free: true,
            created: 1728424000,
            owned_by: "opencode".to_string(),
        },
        ModelMetadata {
            id: "ling-3.0-flash-fin-free".to_string(),
            name: "Ling 3.0 Flash Fin Free".to_string(),
            description: "Financial and analytical reasoning model".to_string(),
            family: "ling".to_string(),
            protocol: ModelProtocol::ChatCompletions,
            reasoning: ReasoningType::Toggle,
            context_limit: 131072,
            output_limit: 16384,
            is_free: true,
            created: 1728424000,
            owned_by: "opencode".to_string(),
        },
        ModelMetadata {
            id: "exo-free".to_string(),
            name: "Exo Free".to_string(),
            description: "High reasoning capacity contributor model".to_string(),
            family: "exo".to_string(),
            protocol: ModelProtocol::ChatCompletions,
            reasoning: ReasoningType::Effort {
                values: vec!["high".to_string()],
            },
            context_limit: 131072,
            output_limit: 16384,
            is_free: true,
            created: 1728424000,
            owned_by: "opencode".to_string(),
        },
        ModelMetadata {
            id: "jev-1.13-free".to_string(),
            name: "Jev 1.13 Free (System One)".to_string(),
            description: "TypeSafe AI System One model for fast, structured decisions".to_string(),
            family: "jev".to_string(),
            protocol: ModelProtocol::SystemOne,
            reasoning: ReasoningType::None,
            context_limit: 131072,
            output_limit: 16384,
            is_free: true,
            created: 1728424000,
            owned_by: "opencode".to_string(),
        },
    ];

    for m in models {
        map.insert(m.id.clone(), m);
    }

    map
}
