use crate::routes::AppState;
use axum::extract::State;
use axum::http::StatusCode;
use axum::response::{IntoResponse, Response};
use axum::Json;
use chrono::Utc;
use serde::Deserialize;
use serde_json::json;

#[derive(Debug, Deserialize)]
pub struct ShowRequest {
    pub name: Option<String>,
    pub model: Option<String>,
}

/// GET /api/tags
pub async fn list_tags(State(state): State<AppState>) -> impl IntoResponse {
    let models = state.registry.list_models().await;
    let aliases = state.registry.get_aliases().await;
    let now_iso = Utc::now().to_rfc3339();

    let mut ollama_models = Vec::new();

    for m in models {
        let tag_name = format!("{}:latest", m.id);
        ollama_models.push(json!({
            "name": tag_name,
            "model": tag_name,
            "modified_at": now_iso,
            "size": 7365960935u64,
            "digest": format!("sha256:{:x}", md5_hash(&m.id)),
            "details": {
                "parent_model": "",
                "format": "gguf",
                "family": m.family,
                "parameter_size": "70B",
                "quantization_level": "Q4_K_M"
            }
        }));
    }

    // Include aliases in Ollama tags as well
    for (alias, _) in aliases {
        let tag_name = format!("{}:latest", alias);
        ollama_models.push(json!({
            "name": tag_name,
            "model": tag_name,
            "modified_at": now_iso,
            "size": 7365960935u64,
            "digest": format!("sha256:{:x}", md5_hash(&alias)),
            "details": {
                "parent_model": "",
                "format": "gguf",
                "family": alias,
                "parameter_size": "70B",
                "quantization_level": "Q4_K_M"
            }
        }));
    }

    Json(json!({ "models": ollama_models }))
}

/// GET /api/version
pub async fn version() -> impl IntoResponse {
    Json(json!({ "version": "0.1.32" }))
}

/// POST /api/show
pub async fn show_model(
    State(state): State<AppState>,
    Json(payload): Json<ShowRequest>,
) -> Response {
    let model_name = payload
        .name
        .or(payload.model)
        .unwrap_or_else(|| "default".to_string());

    let meta = state.registry.resolve_model(&model_name).await;

    let modelfile = format!(
        "# Modelfile generated by rudra-proxy\nFROM {}\nTEMPLATE \"{{{{ .Prompt }}}}\"",
        meta.id
    );

    (
        StatusCode::OK,
        Json(json!({
            "license": "OpenCode Contributor Tier",
            "modelfile": modelfile,
            "parameters": "stop \"<|im_end|>\"",
            "template": "{{ .Prompt }}",
            "details": {
                "parent_model": "",
                "format": "gguf",
                "family": meta.family,
                "parameter_size": "70B",
                "quantization_level": "Q4_K_M"
            },
            "model_info": {
                "general.architecture": meta.family,
                "general.parameter_count": 70000000000u64
            }
        })),
    )
        .into_response()
}

fn md5_hash(s: &str) -> u128 {
    // Generate deterministic 128-bit hash for simulated digest
    let mut h: u128 = 0xcbf29ce484222325;
    for b in s.bytes() {
        h = h.wrapping_mul(0x100000001b3);
        h ^= b as u128;
    }
    h
}
